config/routes.rb
Mangouste::Application.routes.draw do |map|
  match 'welcome/:action' => 'welcome#action'
  resources :cvs

  root :to => "welcome#index"

end

app/models/address.rb
class Address
  include MongoMapper::Document

  key :postal_address,  String
  key :postal_code,     String
  key :town,            String

  belongs_to :person
end

app/models/cv.rb
# a cv has a person with an address and then cv_section( which include cv_items or job_positions)
class Cv
  include MongoMapper::Document

  key :title,     String
  key :subtitle,  String

  # many :cv_sections
  one :person
end

app/models/cv_item.rb
# a cv_item is an item in a cv_section (they share some common attributes title, position) 
class CvItem < CvSection
  include MongoMapper::Document  # FIXME: not necessary ?

  key :title, String
  key :description, String
  key :position, Integer, :numeric=>true, :required=>true
end

app/models/cv_section.rb
# a cv_section delimins the main parts of the CV (profesionnal exp, schools, languages etc.)
class CvSection
  include MongoMapper::Document

  key :title, String
  key :position, Integer, :numeric=>true, :required=>true

  many :cv_items
end

app/models/job_position.rb
# a job_position is a specialized cv_item to represent job positions 
class JobPosition < CvItem
  include MongoMapper::Document # FIXME: not necessary ?

  key :started_on, Date, :required=>true, :allow_blank => false
  key :ended_on, Date, :required=>true, :allow_blank => false
  key :company, String
  key :client, String
  key :location, String
  key :technologies, Array
end

app/models/manager.rb
class Manager < Person

  many :persons # TODO: how to change the name of the relation ? has_many :team_members, :through=>:person
  
end

app/models/person.rb
# http://railstips.org/blog/archives/2009/06/27/mongomapper-the-rad-mongo-wrapper/

class Person #  TODO: or better: employee ?
  include MongoMapper::Document

  key :first_name,      String, :required=>true, :allow_blank => false
  key :last_name,       String, :required=>true, :allow_blank => false
  key :birthdate,       Date
  key :driver_license,  String
  #timestamps! # does not work ?
  
  many :phone_numbers
  belongs_to :manager
  
end

app/models/phone_number.rb
class PhoneNumber
  include MongoMapper::EmbeddedDocument
  
  key :type,  Integer,  :numeric=>true #  0: no type, 1: personal, 2: work
  key :phone, String,   :required=>true
  #timestamps! # does not work ?
  
end

app/models/user.rb
class User < Person
  include MongoMapper::Document
  # FIXME: do we need to include this again as it derives from Person ? See Manager.rb

  key :login,  String, :required=>true, :allow_blank => false
  key :password,  String, :required=>true, :allow_blank => false
  key :email
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cvs_controller.rb
class CvsController < ApplicationController
  # GET /cvs
  # GET /cvs.xml
  def index
    @cvs = Cv.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cvs }
    end
  end

  # GET /cvs/1
  # GET /cvs/1.xml
  def show
    @cv = Cv.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cv }
    end
  end

  # GET /cvs/new
  # GET /cvs/new.xml
  def new
    @cv = Cv.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cv }
    end
  end

  # GET /cvs/1/edit
  def edit
    @cv = Cv.find(params[:id])
    @p = @cv.person
  end

  # POST /cvs
  # POST /cvs.xml
  def create
    @cv = Cv.new(params[:cv])

    # FIXME remove this test
    logger.debug 'adding test person'
    @cv.person = Person.new(:first_name => 'foo', :last_name => 'bar', :driver_license => 'Permis B')

    respond_to do |format|
      if @cv.save
        format.html { redirect_to(@cv, :notice => 'Cv was successfully created.') }
        format.xml  { render :xml => @cv, :status => :created, :location => @cv }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cv.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cvs/1
  # PUT /cvs/1.xml
  def update
    @cv = Cv.find(params[:id])

    respond_to do |format|
      if @cv.update_attributes(params[:cv])
        format.html { redirect_to(@cv, :notice => 'Cv was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cv.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cvs/1
  # DELETE /cvs/1.xml
  def destroy
    @cv = Cv.find(params[:id])
    @cv.destroy

    respond_to do |format|
      format.html { redirect_to(cvs_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def delete_person
    Person.all.first.destroy
    redirect_to :action => "index"
  end

  def create_person
    person = Person.new
    person.first_name = 'foo'
    person.last_name = 'bar'
    person.phone_numbers << PhoneNumber.new(:phone=>"0633XXXXX")
    person.phone_numbers << PhoneNumber.new(:phone=>"0512XXXXX")
    person.save
    redirect_to :action => "index"
  end

  def delete_user
      User.all.first.destroy
      redirect_to :action => "index"
  end

  def create_user
    person = User.new
    person.first_name = 'foo2'
    person.last_name = 'bar2'
    person.login = 'foobar2'
    person.password = 'secret'
    person.save
    redirect_to :action => "index"
  end

  def index
    @persons = Person.all
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cvs/_form.html.erb
<% form_for(@cv) do |f| %>
  <%= f.error_messages %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br />
    <%= f.text_field :subtitle %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cvs/edit.html.erb
<h1>Editing cv</h1>

<%= render 'form' %>

<%= link_to 'Show', @cv %> |
<%= link_to 'Back', cvs_path %>

app/views/cvs/index.html.erb
<h1>Listing cvs</h1>

<table id="cvs">
  <tr>
    <th>Fisrt Name</th>
    <th>Last Name</th>
    <th>Cv Title</th>
    <th>Cv Subtitle</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cvs.each do |cv| %>
  <tr>
    <td><%= cv.person.first_name %></td>
    <td><%= cv.person.last_name %></td>
    <td><%= cv.title %></td>
    <td><%= cv.subtitle %></td>
    <td><%= link_to 'Show', cv %></td>
    <td><%= link_to 'Edit', edit_cv_path(cv) %></td>
    <td><%= link_to 'Destroy', cv, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New cv', new_cv_path %>

app/views/cvs/new.html.erb
<h1>New cv</h1>

<%= render 'form' %>

<%= link_to 'Back', cvs_path %>

app/views/cvs/show.html.erb
<p>
  <b>First Name:</b>
  <%= @cv.person.first_name %>
</p>

<p>
  <b>Last Name:</b>
  <%= @cv.person.last_name %>
</p>

<p>
  <b>Title:</b>
  <%= @cv.title %>
</p>

<p>
  <b>Subtitle:</b>
  <%= @cv.subtitle %>
</p>

<%= link_to 'Edit', edit_cv_path(@cv) %> |
<%= link_to 'Back', cvs_path %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="<%= I18n.locale %>">
    <head>
        <title>[Mangouste] <%= controller.action_name %></title>
        <%= stylesheet_link_tag 'main', :media => 'screen' %>
        <%= stylesheet_link_tag 'cvs', :media => 'screen' %>
        <%= stylesheet_link_tag 'scaffold' %>
        <%= javascript_include_tag :defaults %>
        <%= csrf_meta_tag %>
    </head>
    <body>
        <header>
            <h1>The mangouste project</h1>
        </header>
        <nav>
          <ul>
            <li><%= link_to 'home', :controller => 'welcome' %></li>
            <li><%= link_to 'cvs', :controller => 'cvs' %></li>
          </ul>
        </nav>
        <div id="content">
            <p class="notice"><%= notice %></p>
            <section><%= yield %></section>
        </div>
        <aside></aside>
        <footer>
            <address>Github:<a href="http://github.com/francisoud/mangouste">The mangouste project</a></address>
        </footer>
    </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<!-- table are so web 1.0 ;) -->
<table width="600px"><tr><td>
<p>Persons:
  <ul>
    <% @persons.each do |p| %>
      <li><%= "#{p.first_name} #{p.last_name}" %></li>
    <% end %>
  </ul>
<%= link_to 'create a person', :action => 'create_person' %> - <%= link_to 'delete a person', :action => 'delete_person' %>
</p>
</td><td>
<p>Users:
  <ul>
    <% @users.each do |u| %>
      <li>
        <%= "#{u.login} #{u.password}" %>
        (<%= "#{u.first_name} #{u.last_name}" %>)
      </li>
    <% end %>
  </ul>
<%= link_to 'create a user', :action => 'create_user' %> - <%= link_to 'delete a user', :action => 'delete_user' %>
</p>
</td></tr></table>